name: baseline-tests
run-name: baseline testing
on: [push]
jobs:
  baseline-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Test code
        run: pytest
